### ISSUE TITLE
Helm installation failed with nodeSelector

### ISSUE THREAD

**Issue by perryluopl** [neo4j/helm-charts#290]
Helm installation failed with nodeSelector

**Neo4j Version:** 5.14.0
**Operating System:** EKS 1.27
**API:** Docker

### Steps to reproduce
Inside values.yaml, define:
```
nodeSelector:
  dedicated: openneo4j
  beta.kubernetes.io/instance-type: m5.xlarge
```
  
helm upgrade -i neo4jpoc neo4j/neo4j -f values.yaml -n neo4jpoc --create-namespace --dry-run

### Expected behavior
neo4j should be deployed in the EKS node labeled as openneo4j.

### Actual behavior
Got error.
Error: execution error at (neo4j/templates/_helpers.tpl:80:16): No node exists in the cluster which has all the below labels (.Values.nodeSelector)
 %smap[beta.kubernetes.io/instance-type:m5.xlarge dedicated:openneo4j]
 
 Question: What is %smap?

**Comment by harshitsinghvi22** [comment]
@perryluopl the nodeSelector in helm charts is working fine as expected. I tried out in EKS and the pod is getting scheduled properly.

The error that you are seeing is mainly because of the flag `--dry-run`

The helm charts use the lookup function to check for nodes which have the provided nodeselector. when you use --dry-run this operation will fail since with `--dry-run` flag you cannot talk to the k8s api server hence the lookup fails

You should try removing the --dry-run flag and that should work for you.

If you do have to use the --dry-run flag for some reason you can use the flag `--set disableLookups="true"`
